---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    driver_config:
      box: chef/centos-6.5
  - name: centos-5.10
    driver_config:
      box: chef/centos-5.10

suites:
  - name: default
    data_bags_path: test/integration/default/data_bags
    encrypted_data_bag_secret_key_path: test/integration/default/data_bag_key
    run_list:
      - recipe[munge::default]
    attributes: {}
